approach_task:
  description: >
    Make 5 approaches for {title} when given the {description}
    Make sure to think about why the current idea didn't work and 
  expected_output: >
    A list of 5 approaches to solve
  agent: approach_creater

reward_task:
  description: >
    When given a {solution} for {problem} reason how good the solution is and rate it on a scale of 1 to 10
  expected_output: >
    An integer between 1 and 10 (inclusive)
  agent: reward_generator