approach_task:
  description: >
    Make 5 approaches for title when given the description
    Make sure to think about why the current idea didn't work and 
  expected_output: >
    A list of 5 approaches to solve
  agent: approach_creater

reward_task:
  description: >
    When given a solution for problem reason how good the solution is and rate it on a scale of 1 to 10
  expected_output: >
    An integer between 1 and 10 (inclusive)
  agent: reward_generator

ideation_task:
  description: >
    Given a solution for problem and reward the solution is refined further to maximize reward
  expected_output: >
    A further refined solution (string)
  agent: ideation
  
bestapproach_task:
  description: >
    Given a list of ideas, consider the reward score and reason about the best idea
  expected_output: >
    The best solution, problem, and the reward (string)
  agent: bestapproach

exa_task:
  description: >
    Given a problem and solution you research all the relevant things on the internet
  expected_output: >
    Output everything you found on the internet regarding problem and solution
  agent: exa